# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on: 
  push:
    branches
      - main

jobs:
  check-test-build:
    runs-on: ubuntu-latest
    steps:
      - name : create-directory
        run: mkdir downloads
      - name : checkout
        uses: actions/checkout@v2
        run: |
          ls ${{ github.workspace }} 
          gcc hello.c -o hello
          ./hello
        run: echo "🍏 This job's status is ${{ job.status }}."
        run: cp hello downloads        
