name: GitHub Actions Demo
on:
  push:
    branches:
      - main
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: alexvatti/hello-world-lib
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: lib-artifact
          rename: lib-artifact    
          wait_seconds: 60  
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          unzip lib-artifact.zip 
          gcc hello.c -Lladd -o hello
          ./hello
      - run: echo "This job's status is ${{ job.status }}."
      
      - name : Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: hello
