name: "Publish GitHub Actions Artifacts Example"
true: 
  push: "branches - main" 
  
jobs: 
  check-test-build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: create-directory
        run: "mkdir downloads"
      - 
        name: checkout
        run: "cp hello downloads"
        uses: actions/checkout@v2
      
