name: GitHub Actions Demo
on:
  push:
    branches:
      - main
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request GET \
          "https://api.github.com/repos/alexvatti/hello-world-lib/actions/artifacts/362978694/zip" \ 
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "Accept: application/vnd.github+json"
          
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          cp lib-artifact /* ./ 
          ls lib-artifact*
          gcc hello.c -Lladd -o hello
          ./hello
      - run: echo "This job's status is ${{ job.status }}."
      
      - name : Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: hello
