name: GitHub Actions Demo
on:
  push:
    branches:
      - main
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -JLO \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/alexvatti/hello-world-lib/actions/artifacts/364230672/zip
          
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          unzip lib-artifact.zip 
          ls ${{ github.workspace }}
          gcc hello.c -L./ ladd -o hello
      - run: echo "This job's status is ${{ job.status }}."
      
      - name : Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: hello
