name: GitHub Actions Demo
on:
  push:
    branches:
      - main
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          gcc hello.c -o hello
          ./hello
      - run: echo "This job's status is ${{ job.status }}."
      
      - name : Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: hello
