name: GitHub Actions Demo
on:
  push:
    branches:
      - main
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          gcc hello.c -o hello
          ./hello
      - run: echo "This job's status is ${{ job.status }}."
      
      - name: Download artifact from build
        uses: actions/download-artifact@v3
        with:
          repo: alexvatti/hello-world
          artifact_name: my-artifact
          rename: new-artifact-name    
          wait_seconds: 60  
